/******************************************************************************
*                                                                             *
*                _  _               ___             _             			      *
*               (_)| |__   _ __    / _ \ _ __ ___  | |__    /\  /\			      *
*               | || '_ \ | '__|  / /_\/| '_ ` _ \ | '_ \  / /_/ /            *
*               | || | | || |    / /_\\ | | | | | || |_) |/ __  / 			      *
*               |_||_| |_||_|    \____/ |_| |_| |_||_.__/ \/ /_/  			      *
*                                                                             *
*  ihr GmbH                                                                   *
*  Airport Boulevard B210                                                     *
*  77836 Rheinmünster - Germany                                               *
*  http://www.ihr.de                                                          *
*  Phone +49(0) 7229-18475-0                                                  *
*  Fax   +49(0) 7229-18475-11                                                 *
*                                                                             *
*******************************************************************************/
// Generated by LDC Full Version Version 1.4.3.2
// Generated from LDF: ATEV_AL_V2.1df
#include "genLinConfig.h"


//t_lin_sched_table schedule0[3] = {{17,2176,80},{146,2176,80},{226,2176,80}};    //this schedule should be config by PC
t_lin_sched_table schedule0[LIN_MAX_NUM];

//t_lin_sched_table schedule1[5] = {{17,2176,100},{146,2176,100},{97,640,100},{226,640,100},{163,640,100}};
//t_lin_sched_table schedule2[2] = {{60,2048,100},{125,2048,100}};
//t_lin_sched_table schedule3[1] = {{125,2048,100}};
//t_lin_sched_table schedule4[1] = {{60,2048,100}};
//t_lin_sched_table schedule5[1] = {{60,2048,1000}};
//t_lin_sched_table schedule6[1] = {{125,2048,1000}};
l_u8 schedTblSizeList[1];
l_ScheduleTableList* scheduleList[1];
void Init_ScheduleTableList(void)
{
  scheduleList[0] = (l_ScheduleTableList*)schedule0;
//  scheduleList[1] = (l_ScheduleTableList*)schedule1;
//  scheduleList[2] = (l_ScheduleTableList*)schedule2;
//  scheduleList[3] = (l_ScheduleTableList*)schedule3;
//  scheduleList[4] = (l_ScheduleTableList*)schedule4;
//  scheduleList[5] = (l_ScheduleTableList*)schedule5;
//  scheduleList[6] = (l_ScheduleTableList*)schedule6;
}


//t_l_node_diag_info slv1 = {{0,33,768,8481,1500,500}};
//t_l_conf_frame_info cfg_frms_slv1[3] = {{{1,0,17}},{{2,0,146}},{{3,0,97}}};
//t_l_node_diag_info slv2 = {{0,34,768,8738,1500,500}};
//t_l_conf_frame_info cfg_frms_slv2[3] = {{{4,0,17}},{{5,0,146}},{{6,0,226}}};
//t_l_node_diag_info slv3 = {{0,35,768,8995,1500,500}};
//t_l_conf_frame_info cfg_frms_slv3[3] = {{{7,0,17}},{{8,0,146}},{{9,0,163}}};
//t_l_node_diag_info_list l_node_diag_info_list[3]={&slv1,&slv2,&slv3};
//t_l_conf_frm_info_list l_conf_frm_info_list[3]={cfg_frms_slv1,cfg_frms_slv2,cfg_frms_slv3};

//volatile t_l_flags_LedColorCtrl l_flags_LedColorCtrl;

//volatile t_l_flags_LedFlowCtrl l_flags_LedFlowCtrl;

//volatile t_l_flags_Slave1_Left_States l_flags_Slave1_Left_States;

//volatile t_l_flags_Slave2_Center_States l_flags_Slave2_Center_States;

//volatile t_l_flags_Slave3_Right_States l_flags_Slave3_Right_States;

//t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT [LIN_NUMBER_OF_FRAMES] = {{{17,129,8}},{{146,129,8}},{{97,128,2}},{{226,129,2}},{{163,128,2}}};//here should be changed
t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT [LIN_MAX_NUM];   //129是发送主任务，128是接收从任务

// define generated lin data variables with init value
/*
t_l_Lin_Data const_LinData = {{0, 0, 0, 0, 0, 0, 255, 255,
																	 	 0, 0, 0, 0, 0, 0, 0, 0,
																		 226, 254, 255, 255, 255, 255, 255, 255,
																		 226, 254, 255, 255, 255, 255, 255, 255,
																		 226, 254, 255, 255, 255, 255, 255, 255}};

t_l_Lin_Data l_LinData =	{{0, 0, 0, 0, 0, 0, 255, 255,
													  0, 0, 0, 0, 0, 0, 0, 0,
													  226, 254, 255, 255, 255, 255, 255, 255,
													  226, 254, 255, 255, 255, 255, 255, 255,
													  226, 254, 255, 255, 255, 255, 255, 255}};
*/
t_l_Lin_Data const_LinData;

t_l_Lin_Data l_LinData;

